name: TimerPlugin
version: '${project.version}'
main: me.termalquake.TimerPlugin
api-version: 1.20
authors: [TermalQuake]
commands:
  timer:
    description: Устанавливает таймер и таблички
    usage: /<command> <x1> <y1> <z1> <x2> <y2> <z2>
