name: playedtimesigns
version: '1.1-SNAPSHOT'
main: me.termalquake.PlayedTimeSign
api-version: '1.21'
authors: [ termalquake ]
description: opisanue
website: aperture.su

commands:
  signplayed:
    permission: op
    description: Устанавливает таблички с топ игроками
    usage: /signplayed <x1-y1-z1> <x2-y2-z2> <+x/+z/-x/-z>
  signreload:
    description: Перезагрузка плагина SignPlayed
    permission: signplayed.reload
    usage: /signreload
