name: TimerPlugin
version: '1.0-SNAPSHOT'
main: me.termalquake.TimerPlugin
api-version: 1.20
commands:
  timer:
    description: Устанавливает таймер и таблички
    usage: /<command> <x1> <y1> <z1> <x2> <y2> <z2>
